/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Model.BusModel;
import Services.BusIntrf;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gertrude
 */
public class Bus extends javax.swing.JFrame {

     private DefaultTableModel table = new DefaultTableModel();
    /**
     * Creates new form Bus
     */
    public Bus() {
        initComponents();
        addColumn();
        addRows();
    }
  
     public void addColumn(){
        table.addColumn("Car ID");
        table.addColumn("Model");
        table.addColumn("Route");
        table.addColumn("Price");
        table.addColumn("Departure Date");
        table.addColumn("Departure Time");
        table.addColumn("Arrival Time");
        table.addColumn("Available Seats");
        bus_table.setModel(table);    
    }
     ///method for adding rows in table
    public void addRows(){  
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            BusIntrf service  = (BusIntrf)registry.lookup("Bus");
            List<BusModel> busList = service.allBus();
          
          
            if(busList!=null){
                  Iterator iterator = busList.iterator();
                 while (iterator.hasNext()){
                BusModel cars = (BusModel)iterator.next();
                table.addRow(new Object[]{
                   cars.getBusId(),
                   cars.getModel(),
                   cars.getRoute(),
                   cars.getPrice(),
                   cars.getDeparture_date(),
                   cars.getDeparture_time(),
                   cars.getArrival_time(),
                   cars.getSeats()
               
                });
                bus_table.setModel(table);  
            }
           
            
            }
          
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modelTxt = new javax.swing.JTextField();
        departureTime = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        seatsTxt = new javax.swing.JTextField();
        routeTxt = new javax.swing.JTextField();
        carIdTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        arrivalTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bus_table = new javax.swing.JTable();
        createReport1 = new javax.swing.JButton();

        jButton5.setBackground(new java.awt.Color(153, 204, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        jButton5.setText("BUY");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 137, 27));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bus Information");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please fill this form for Bus information!!");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("Car ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setText("Model");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("Departure Time");

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel8.setText("available seats");

        modelTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        departureTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        priceTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 102));
        updateBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(0, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(153, 204, 0));
        saveBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        saveBtn.setText("Register");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setText("Price");

        seatsTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        routeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        carIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel14.setText("Departure Date");

        arrivalTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 51, 51));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("Route");

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel15.setText("Arrival Time");

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 51));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel14)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carIdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(modelTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(routeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seatsTxt)
                    .addComponent(departureTime)
                    .addComponent(arrivalTxt))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(saveBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(arrivalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(80, 80, 80))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/horizonLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(560, 560, 560))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 137, 27));
        jLabel10.setText("Driver Details");

        refreshBtn.setBackground(new java.awt.Color(0, 153, 51));
        refreshBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        searchBtn1.setBackground(new java.awt.Color(0, 153, 153));
        searchBtn1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel11.setText("Search ID:");

        bus_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bus_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bus_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bus_table);

        createReport1.setBackground(new java.awt.Color(0, 153, 51));
        createReport1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        createReport1.setForeground(new java.awt.Color(255, 255, 255));
        createReport1.setText("Print");
        createReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createReport1MouseClicked(evt);
            }
        });
        createReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReport1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(144, 144, 144))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createReport1)
                .addGap(312, 312, 312))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBtn1)
                        .addComponent(refreshBtn))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createReport1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        try{
            String time = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            int seats = Integer.parseInt(seatsTxt.getText());
            
            if(carIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(modelTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Model is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(routeTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Route is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(priceTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Price is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(time.trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "Departure Date is required");
            }
            else if(arrivalTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Arrival Time is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(departureTime.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Departure Time is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
              else if(seatsTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Seats is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            
            else{
                if(carIdTxt.getText().length()!=7){
                    JOptionPane.showMessageDialog(this, "ID should be 7 characters","INVALID ID" ,
                            JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(!carIdTxt.getText().startsWith("RA")){
                        JOptionPane.showMessageDialog(this, "Should start with RA","INVALID PHONE NUMBER",
                            JOptionPane.ERROR_MESSAGE );      
                    }
                    
                    else{
                        if(seats!=25){
                            JOptionPane.showMessageDialog(this, "Available Seats should be 25","INVALID SEATS NUMBER",
                            JOptionPane.ERROR_MESSAGE ); 
                        }
                        else{
                        
                                double price = Double.parseDouble(priceTxt.getText());
                               // int seats = Integer.parseInt(seatsTxt.getText());
                                BusModel car = new BusModel();
                                car.setBusId(carIdTxt.getText());
                                car.setModel(modelTxt.getText());
                                car.setRoute(routeTxt.getText());
                                car.setPrice(price);
                                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                DateChooser.getJCalendar().setMinSelectableDate(new Date());
                                DateChooser.setMinSelectableDate(new Date());
                                  //DateChooser.getDateEditor().setEnabled(false);
                                DateChooser.setMaxSelectableDate(null);
                                Date date = dateFormat.parse(time);
                                 
                                car.setDeparture_date(date);
                                car.setArrival_time(arrivalTxt.getText());
                                car.setDeparture_time(departureTime.getText());
                                car.setSeats(seats);
                                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                BusIntrf service = (BusIntrf)registry.lookup("Bus");
                                String feedback = service.registerBus(car);

                                JOptionPane.showMessageDialog(this, feedback);
                            }
                    }
                            
                        }
                    
                    
                
               
            }
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        //set table to 0 rows
        table.setRowCount(0);
        //adding rows
        addRows();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        carIdTxt.setText("");
        modelTxt.setText("");
        routeTxt.setText("");
        ((JTextField)DateChooser.getDateEditor().getUiComponent()).setText("");
        priceTxt.setText("");
        arrivalTxt.setText("");
        departureTime.setText("");
        searchTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try{
            String time = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            
            if(carIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(modelTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Model is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(routeTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Route is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(priceTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Price is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(time.trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "Departure Date is required");
            }
            else if(arrivalTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Arrival Time is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(departureTime.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Departure Time is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
              else if(seatsTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Seats is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            
            else{
                if(carIdTxt.getText().length()!=7){
                    JOptionPane.showMessageDialog(this, "ID should be 7 characters","INVALID ID" ,
                            JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(!carIdTxt.getText().startsWith("RA")){
                        JOptionPane.showMessageDialog(this, "Should start with RA","INVALID PHONE NUMBER",
                            JOptionPane.ERROR_MESSAGE );      
                    }
                    
                        
                            else{
                                 double price = Double.parseDouble(priceTxt.getText());
                                int seats = Integer.parseInt(seatsTxt.getText());
                                BusModel car = new BusModel();
                                car.setBusId(carIdTxt.getText());
                                car.setModel(modelTxt.getText());
                                car.setRoute(routeTxt.getText());
                                car.setPrice(price);
                                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                Date date = dateFormat.parse(time);
                                car.setDeparture_date(date);
                                car.setArrival_time(arrivalTxt.getText());
                                car.setDeparture_time(departureTime.getText());
                                car.setSeats(seats);
                                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                BusIntrf service = (BusIntrf)registry.lookup("Bus");
                                String feedback = service.updateBus(car);

                                JOptionPane.showMessageDialog(this, feedback);
                            }
                            
                        }
           
            }
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            String time = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            
            
                    if(!carIdTxt.getText().startsWith("RA")){
                        JOptionPane.showMessageDialog(this, "Should start with RA","INVALID PHONE NUMBER",
                            JOptionPane.ERROR_MESSAGE );      
                    }
                    
                        
                    else{
                         int option = JOptionPane.showConfirmDialog(this, "Are sure you want to delete this Bus", "Delete Confirmation"
                             , JOptionPane.YES_NO_OPTION);
           
                        if(option == 0){
                                 double price = Double.parseDouble(priceTxt.getText());
                                int seats = Integer.parseInt(seatsTxt.getText());
                                BusModel car = new BusModel();
                                car.setBusId(carIdTxt.getText());
                                car.setModel(modelTxt.getText());
                                car.setRoute(routeTxt.getText());
                                car.setPrice(price);
                                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                Date date = dateFormat.parse(time);
                                car.setDeparture_date(date);
                                car.setArrival_time(arrivalTxt.getText());
                                car.setDeparture_time(departureTime.getText());
                                car.setSeats(seats);
                                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                BusIntrf service = (BusIntrf)registry.lookup("Bus");
                                String feedback = service.deleterBus(car);

                                JOptionPane.showMessageDialog(this, feedback);
                            }
                            else{
                            JOptionPane.showMessageDialog(this, "Data is not deleted successfully");
                            }
                    }
                    
                    
                    
                
               
            
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void bus_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus_tableMouseClicked
        try{
            //set data to their texfield
            DefaultTableModel table = (DefaultTableModel)bus_table.getModel();
           
            String ID = table.getValueAt(bus_table.getSelectedRow(),0).toString();
            String model = table.getValueAt(bus_table.getSelectedRow(),1).toString();
            String route = table.getValueAt(bus_table.getSelectedRow(),2).toString();
            String price = table.getValueAt(bus_table.getSelectedRow(),3).toString();
            String date = table.getValueAt(bus_table.getSelectedRow(),4).toString();
            String depart = table.getValueAt(bus_table.getSelectedRow(),5).toString();
            String arrival = table.getValueAt(bus_table.getSelectedRow(),6).toString();
            String seats = table.getValueAt(bus_table.getSelectedRow(),7).toString();

         carIdTxt.setText(ID);
        modelTxt.setText(model);
        routeTxt.setText(route);
        ((JTextField)DateChooser.getDateEditor().getUiComponent()).setText(date);
        priceTxt.setText(price);
        arrivalTxt.setText(arrival);
        departureTime.setText(depart);
        seatsTxt.setText(seats);
            
             
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_bus_tableMouseClicked

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        try{
            
            BusModel car = new BusModel();
            car.setBusId(searchTxt.getText());
             
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            BusIntrf service = (BusIntrf)registry.lookup("Bus");
            BusModel buses = service.searchId(car);
            //set table to 0 rows
            table.setRowCount(0);
            if(buses != null){
               table.addRow(new Object[]{
                    buses.getBusId(),
                  
                   buses.getModel(),
                   buses.getRoute(),
                   buses.getPrice(),
                   buses.getDeparture_date(),
                   buses.getDeparture_time(),
                   buses.getArrival_time(),
                   buses.getSeats()
                    
                });
            }
        }catch(Exception exe){
            exe.printStackTrace();
        }
        
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ManagerChoose form = new ManagerChoose();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createReport1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createReport1MouseClicked

    private void createReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReport1ActionPerformed
        // TODO add your handling code here:
        try{
            bus_table.print();
             JOptionPane.showMessageDialog(this, "Data printed successfully");
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_createReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bus_table;
    private javax.swing.JTextField carIdTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton createReport1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField departureTime;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField routeTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField seatsTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
