/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Model.BusModel;
import Model.DriverModel;
import Services.BusIntrf;
import Services.DriverIntrf;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gertrude
 */
public class Driver extends javax.swing.JFrame {
    
     private DefaultTableModel table = new DefaultTableModel();
    

    /**
     * Creates new form Driver
     */
    public Driver() {
       
        initComponents();
        addColumn();
        addRows();
        addItemCombo();
    }
     private void addItemCombo(){
        try{
            busCombo.removeAllItems();
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            BusIntrf service = (BusIntrf)registry.lookup("Bus");
            List<BusModel> buses = service.allBus();
            if(buses != null){
                for(BusModel bus: buses){
                    busCombo.addItem(bus.getBusId());
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
     public void addColumn(){
        table.addColumn("Driver ID");
        table.addColumn("First Name");
        table.addColumn("Last Name");
        table.addColumn("Date Of Birth");
        table.addColumn("Phone Number");
        table.addColumn("Bus Plack");
        driver_table.setModel(table);    
    }
     ///method for adding rows in table
    public void addRows(){  
        try{
            
            Registry registry = LocateRegistry.getRegistry(81);
            DriverIntrf service  = (DriverIntrf)registry.lookup("Driver");
            List<DriverModel> driverList = service.allDrivers();
            //List<DriverModel> carList = service.selectedBus();
            
            
            Iterator iterator = driverList.iterator();
            
            
            
           // String busData = DriverIntrf.fetchBusData(busId);
          
            while (iterator.hasNext()){
                DriverModel drove = (DriverModel)iterator.next();
                    //String foreignKeyData = drove.getBus().getBusId();// Fetch the related data for the foreign key

                String foreignKeyData = null;
                if (drove != null && drove.getBus() != null) {
                    foreignKeyData = drove.getBus().getBusId();
                }
                table.addRow(new Object[]{
                   drove.getDriverId(),
                    drove.getFirstName(),
                    drove.getLastName(),
                    drove.getDOB(),
                    drove.getPhone_number(),
                    //drove.getBus().getBusId()
                    foreignKeyData
                  
                });
            
            }
          driver_table.setModel(table);  
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstnameTxt = new javax.swing.JTextField();
        driverIdTxt = new javax.swing.JTextField();
        lastnameTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        busCombo = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        driver_table = new javax.swing.JTable();
        createReport1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 137, 27));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("Driver ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("DOB");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("First Name");

        firstnameTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtActionPerformed(evt);
            }
        });

        driverIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverIdTxtActionPerformed(evt);
            }
        });

        lastnameTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTxtActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(153, 204, 0));
        registerBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 102));
        updateBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(0, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Driver Information");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setText("Phone Number");

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 51, 51));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        DateChooser.setDateFormatString("yyyy-MM-dd");

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel10.setText("Bus Plack");

        busCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 51));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(driverIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(61, 61, 61)
                                .addComponent(firstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(26, 26, 26)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(73, 73, 73)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(phoneTxt)
                                    .addComponent(busCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(driverIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn))
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(21, 21, 21)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(busCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(319, 319, 319))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/horizonLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 137, 27));
        jLabel1.setText("Driver Details");

        refreshBtn.setBackground(new java.awt.Color(0, 153, 51));
        refreshBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("REFRESH");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        searchBtn1.setBackground(new java.awt.Color(0, 153, 153));
        searchBtn1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel9.setText("Search ID:");

        driver_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        driver_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driver_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(driver_table);

        createReport1.setBackground(new java.awt.Color(0, 153, 51));
        createReport1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        createReport1.setForeground(new java.awt.Color(255, 255, 255));
        createReport1.setText("Print");
        createReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createReport1MouseClicked(evt);
            }
        });
        createReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReport1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(18, 18, 18)
                .addComponent(createReport1)
                .addGap(53, 53, 53))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBtn1)
                        .addComponent(refreshBtn)
                        .addComponent(createReport1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtActionPerformed

    private void driverIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverIdTxtActionPerformed

    private void lastnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
       
        try{
            String dob = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            String age[] = dob.split("-");  
            int year = Integer.parseInt(age[0]);
            if(driverIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(firstnameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "First Name is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(lastnameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Last Name is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
           else if(phoneTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Phone Number is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(dob.trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "DOB is required");
            }
            
            else{
                if(driverIdTxt.getText().length()!=5){
                    JOptionPane.showMessageDialog(this, "ID should be 5 characters","INVALID ID" ,
                            JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(!phoneTxt.getText().startsWith("+25")){
                        JOptionPane.showMessageDialog(this, "Should start with +250","INVALID PHONE NUMBER",
                            JOptionPane.ERROR_MESSAGE );      
                    }
                    else{
                       if(phoneTxt.getText().length()!=13){
                        JOptionPane.showMessageDialog(this, "Should be 13 characters","INVALID PHONE NUMBER",JOptionPane.ERROR_MESSAGE);
                    }
                        else{
                            if(year>2002 || year<1968){
                            JOptionPane.showMessageDialog(this, "Minimum age is 18 an maximum age is 55", "Data Required",
                            JOptionPane.ERROR_MESSAGE);
                            }
                            
                            else{
                                 DriverModel drive = new DriverModel();
                                drive.setDriverId(driverIdTxt.getText());
                                drive.setFirstName(firstnameTxt.getText());
                                drive.setLastName(lastnameTxt.getText());
                                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                Date date = dateFormat.parse(dob);
                                drive.setDOB(date);
                                drive.setPhone_number(phoneTxt.getText());
                                String plack = busCombo.getSelectedItem().toString(); 
                                BusModel mans=new BusModel(plack);
                                drive.setBus(mans);
                                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                //DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                                DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                                String feedback = service.registerDrivers(drive);

                                JOptionPane.showMessageDialog(this, feedback);
                            }
                            
                        }
                    }
                    
                }
               
            }
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         try{
            String dob = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            String age[] = dob.split("-");  
            int year = Integer.parseInt(age[0]);
            if(driverIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "ID is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(firstnameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "First Name is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(lastnameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Last Name is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(phoneTxt.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Phone Number is required", "Data Required",
                        JOptionPane.WARNING_MESSAGE);
            }
            else if(dob.trim().isEmpty()){
               JOptionPane.showMessageDialog(this, "DOB is required");
            }
            
            else{
                if(driverIdTxt.getText().length()!=5){
                    JOptionPane.showMessageDialog(this, "ID should be 5 characters","INVALID ID" ,
                            JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(!phoneTxt.getText().startsWith("+25")){
                        JOptionPane.showMessageDialog(this, "Should start with +250","INVALID PHONE NUMBER",
                            JOptionPane.ERROR_MESSAGE );      
                    }
                    else{
                       if(phoneTxt.getText().length()!=13){
                        JOptionPane.showMessageDialog(this, "Should be 13 characters","INVALID PHONE NUMBER",JOptionPane.ERROR_MESSAGE);
                    }
                        else{
                            if(year>2002 || year<1968){
                            JOptionPane.showMessageDialog(this, "Minimum age is 18 an maximum age is 55", "Data Required",
                            JOptionPane.ERROR_MESSAGE);
                            }
                            
                            else{
                                 DriverModel drive = new DriverModel();
                                drive.setDriverId(driverIdTxt.getText());
                                drive.setFirstName(firstnameTxt.getText());
                                drive.setLastName(lastnameTxt.getText());
                                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                                Date date = dateFormat.parse(dob);
                                drive.setDOB(date);
                                drive.setPhone_number(phoneTxt.getText());
                                String plack = busCombo.getSelectedItem().toString(); 
                                BusModel man=new BusModel(plack);
                                drive.setBus(man);
                                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                //DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                                DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                                String feedback = service.updateDrivers(drive);

                                JOptionPane.showMessageDialog(this, feedback);
                            }
                            
                        }
                    }
                    
                }
               
            }
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
           try{
            String dob = ((JTextField)DateChooser.getDateEditor().getUiComponent()).getText() ;
            
            int option = JOptionPane.showConfirmDialog(this, "Are sure you want to delete this Driver", "Delete Confirmation"
                    , JOptionPane.YES_NO_OPTION);
           
            if(option == 0){
                 DriverModel drive = new DriverModel();
                 drive.setDriverId(driverIdTxt.getText());
                 drive.setFirstName(firstnameTxt.getText());
                drive.setLastName(lastnameTxt.getText());
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = dateFormat.parse(dob);
                drive.setDOB(date);
                drive.setPhone_number(phoneTxt.getText());
                String plack = busCombo.getSelectedItem().toString(); 
                                BusModel man=new BusModel(plack);
                                drive.setBus(man);
                Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
                                //DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
                String feedback = service.deleteDrivers(drive);

                JOptionPane.showMessageDialog(this, feedback);
            }
             else{
                JOptionPane.showMessageDialog(this, "Data is not deleted successfully");
              }
          
                            
                        
                    
                    
                
               
            
            
        }catch(Exception exe){
            exe.printStackTrace();
        } 
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked

        //set table to 0 rows
        table.setRowCount(0);
        //adding rows
        addRows();

    }//GEN-LAST:event_refreshBtnMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
       //table.setRowCount(0);
       // addRows();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
         try{
            
            DriverModel car = new DriverModel();
            car.setDriverId(searchTxt.getText());
             
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            DriverIntrf service = (DriverIntrf)registry.lookup("Driver");
            DriverModel buses = service.searchId(car);
            //set table to 0 rows
            table.setRowCount(0);
            if(buses != null){
               table.addRow(new Object[]{
                    buses.getDriverId(),
                  
                   buses.getFirstName(),
                   buses.getLastName(),
                   buses.getDOB(),
                   buses.getPhone_number(),
                   buses.getBus().getBusId(),
                   
                    
                });
            }
        }catch(Exception exe){
            exe.printStackTrace();
        }
            
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        driverIdTxt.setText("");
        firstnameTxt.setText("");
        lastnameTxt.setText("");
        ((JTextField)DateChooser.getDateEditor().getUiComponent()).setText("");
        firstnameTxt.setText(""); 
        lastnameTxt.setText(""); 
        phoneTxt.setText("");
        searchTxt.setText("");
        busCombo.setSelectedItem(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void driver_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driver_tableMouseClicked
       try{
            //set data to their texfield
            DefaultTableModel table = (DefaultTableModel)driver_table.getModel();
           
            String ID = table.getValueAt(driver_table.getSelectedRow(),0).toString();
            String fname = table.getValueAt(driver_table.getSelectedRow(),1).toString();
            String lname = table.getValueAt(driver_table.getSelectedRow(),2).toString();
            String age = table.getValueAt(driver_table.getSelectedRow(),3).toString();
            String phone = table.getValueAt(driver_table.getSelectedRow(),4).toString();
            String bs = table.getValueAt(driver_table.getSelectedRow(),5).toString();

           driverIdTxt.setText(ID);
           firstnameTxt.setText(fname);
           lastnameTxt.setText(lname);
           ((JTextField)DateChooser.getDateEditor().getUiComponent()).setText(age);
           phoneTxt.setText(phone);
            busCombo.setSelectedItem(bs);
             
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_driver_tableMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ManagerChoose form = new ManagerChoose();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createReport1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createReport1MouseClicked

    private void createReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReport1ActionPerformed
        // TODO add your handling code here:
        try{
            driver_table.print();
            JOptionPane.showMessageDialog(this, "Data printed successfully");
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_createReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> busCombo;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton createReport1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField driverIdTxt;
    private javax.swing.JTable driver_table;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
