/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CustomerModel;
import Services.CustomerIntrf;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gertrude
 */
public class ViewCustomer extends javax.swing.JFrame {
    private DefaultTableModel table = new DefaultTableModel();

    /**
     * Creates new form ViewCustomer
     */
    public ViewCustomer() {
        initComponents();
        addColumn();
        addRows();
    }
    
     public void addColumn(){
        table.addColumn("ID");
        table.addColumn("First Name");
        table.addColumn("Last Name");
        table.addColumn("Address");
        table.addColumn("Contact");
        table.addColumn("Route");
        table.addColumn("Departure Date");
        table.addColumn("Departure Time");
        table.addColumn("bus ID");
        table.addColumn("Seat No");
        table.addColumn("Payment Method");
        customer_table.setModel(table);    
    }
     ///method for adding rows in table
    public void addRows(){  
        try{
            
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            CustomerIntrf service  = (CustomerIntrf)registry.lookup("Customer");
            List<CustomerModel> customerList = service.allCustomer();
            
             if(customerList!=null){
                  Iterator iterator = customerList.iterator();
                 while (iterator.hasNext()){
                CustomerModel custo = (CustomerModel)iterator.next();
                table.addRow(new Object[]{
                   custo.getCustomerId(),
                    custo.getFirst_name(),
                    custo.getLast_name(),
                    custo.getAddress(),
                    custo.getContact(),
                    //custo.getRoute(),
                    //custo.getDeparture_date(),
                    //custo.getDeparture_time(),
                   
                    custo.getBuse().getBusId(),
                     custo.getBuse().getRoute(),
                    custo.getBuse().getDeparture_date(),
                    custo.getBuse().getDeparture_time(),
                    custo.getSeat_no(),
                    custo.getPayment_method()
               
               
                });
            
          customer_table.setModel(table);  
                 }
             }
            
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn1 = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        createReport = new javax.swing.JButton();
        createReport1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customer_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customer_table);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 137, 27));
        jLabel1.setText("Customer Details");

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel9.setText("Search ID:");

        searchBtn1.setBackground(new java.awt.Color(0, 153, 153));
        searchBtn1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("SEARCH");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(0, 153, 51));
        refreshBtn.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("REFRESH");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 51));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createReport.setBackground(new java.awt.Color(0, 153, 51));
        createReport.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        createReport.setForeground(new java.awt.Color(255, 255, 255));
        createReport.setText("Create Customer Pdf");
        createReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createReportMouseClicked(evt);
            }
        });
        createReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportActionPerformed(evt);
            }
        });

        createReport1.setBackground(new java.awt.Color(0, 153, 51));
        createReport1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        createReport1.setForeground(new java.awt.Color(255, 255, 255));
        createReport1.setText("Print");
        createReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createReport1MouseClicked(evt);
            }
        });
        createReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReport1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(35, 35, 35)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(searchBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(refreshBtn))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(createReport, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(createReport1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn1)
                            .addComponent(refreshBtn)
                            .addComponent(backBtn)
                            .addComponent(createReport))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(createReport1)
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/horizonLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        try{

            CustomerModel cus = new CustomerModel();
            int id = Integer.parseInt(searchTxt.getText());
            cus.setCustomerId(id);

            Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
            CustomerIntrf service = (CustomerIntrf)registry.lookup("Customer");
            CustomerModel custo = service.searchId(cus);
            //set table to 0 rows
            table.setRowCount(0);
            if(custo != null){
               table.addRow(new Object[]{
                   custo.getCustomerId(),
                    custo.getFirst_name(),
                    custo.getLast_name(),
                    custo.getAddress(),
                    custo.getContact(),
                    //custo.getRoute(),
                    //custo.getDeparture_date(),
                    //custo.getDeparture_time(),
                    
                    custo.getBuse().getBusId(),
                     custo.getBuse().getRoute(),
                    custo.getBuse().getDeparture_date(),
                    custo.getBuse().getDeparture_time(),
                    custo.getSeat_no(),
                    custo.getPayment_method()
                       });
           
                }
        }catch(Exception exe){
            exe.printStackTrace();
        }

    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked

        //set table to 0 rows
        table.setRowCount(0);
        //adding rows
        addRows();
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        //table.setRowCount(0);
        // addRows();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
          view.ManagerChoose form = new view.ManagerChoose();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createReportMouseClicked

    private void createReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReportActionPerformed
        // TODO add your handling code here:
//        try{
//             Registry registry = LocateRegistry.getRegistry("127.0.0.1",81);
//            CustomerIntrf service  = (CustomerIntrf)registry.lookup("Customer");
//            List<CustomerModel> customerList = service.allCustomer();
//            report(customerList);
//        }catch(Exception exe){
//            exe.printStackTrace();
//        }
    }//GEN-LAST:event_createReportActionPerformed

    private void customer_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_tableMouseClicked

    private void createReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createReport1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createReport1MouseClicked

    private void createReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReport1ActionPerformed
        // TODO add your handling code here:
        try{
            customer_table.print();
             JOptionPane.showMessageDialog(this, "Data printed successfully");
        }catch(Exception exe){
            exe.printStackTrace();
        }
    }//GEN-LAST:event_createReport1ActionPerformed

    public void report(List<CustomerModel> customerList){
//        try {
//        // Create a file chooser to select the save location
//        JFileChooser fileChooser = new JFileChooser();
//        int result = fileChooser.showSaveDialog(this);
//
//        if (result == JFileChooser.APPROVE_OPTION) {
//            // Get the selected file
//            File file = fileChooser.getSelectedFile();
//
//            // Append the ".pdf" extension if not already present
//            if (!file.getAbsolutePath().endsWith(".pdf")) {
//                file = new File(file.getAbsolutePath() + ".pdf");
//            }
//
//            // Create a new PDF document
//            Document document = new Document();
//            PdfWriter.getInstance(document, new FileOutputStream(file));
//            document.open();
//
//            // Write the table data to the PDF document
//            for (CustomerModel data : customerList) {
//                document.add(new Paragraph(data.toString()));
//            }
//
//            // Close the PDF document
//            document.close();
//        }}catch(Exception exe){
//            exe.printStackTrace();
//        }


    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createReport;
    private javax.swing.JButton createReport1;
    private javax.swing.JTable customer_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
